import type {
  AppointmentSummary,
  TenantPublicProfile,
  TenantSummary,
} from "@/lib/types";

export const tenants: TenantSummary[] = [
  {
    id: "tenant_dentista",
    name: "Clinica Dental Sonrisa",
    slug: "dentista",
    status: "ACTIVE",
    domain: "dentista.com",
    upcomingAppointments: 18,
  },
  {
    id: "tenant_abogado",
    name: "Estudio Lopez & Asociados",
    slug: "abogado",
    status: "TRIAL",
    domain: undefined,
    upcomingAppointments: 4,
  },
];

export const tenantAppointments: AppointmentSummary[] = [
  {
    id: "app_1",
    serviceId: "srv_1",
    serviceName: "Limpieza dental",
    providerId: "prov_1",
    providerName: "Dra. Paula Gomez",
    providerColor: "#5d3fd3",
    customerName: "Maria Gomez",
    customerEmail: "maria@example.com",
    customerPhone: "+54 11 5555-0101",
    startsAt: "2026-04-07 09:00",
    startsAtIso: "2026-04-07T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "APPROVED",
    events: [],
    reminders: [],
  },
  {
    id: "app_2",
    serviceId: "srv_2",
    serviceName: "Control general",
    providerId: "prov_2",
    providerName: "Dr. Martin Lopez",
    providerColor: "#2784e6",
    customerName: "Juan Perez",
    customerEmail: "juan@example.com",
    customerPhone: "+54 11 5555-0130",
    startsAt: "2026-04-07 11:30",
    startsAtIso: "2026-04-07T11:30:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "NOT_REQUIRED",
    events: [],
    reminders: [],
  },
  {
    id: "app_3",
    serviceId: "srv_3",
    serviceName: "Blanqueamiento",
    providerId: "prov_1",
    providerName: "Dra. Paula Gomez",
    providerColor: "#5d3fd3",
    customerName: "Lucia Diaz",
    customerEmail: "lucia@example.com",
    customerPhone: "+54 11 5555-0160",
    startsAt: "2026-04-07 16:00",
    startsAtIso: "2026-04-07T16:00:00.000Z",
    status: "PENDING",
    paymentStatus: "PENDING",
    notes: "Prefiere atencion por la tarde.",
    events: [],
    reminders: [],
  },
];

export const tenantProviders = [
  {
    id: "prov_1",
    name: "Dra. Paula Gomez",
    email: "admin@dentista.com",
    phone: "+54 11 4444-1101",
    color: "#5d3fd3",
    isActive: true,
  },
  {
    id: "prov_2",
    name: "Dr. Martin Lopez",
    email: "martin@dentista.com",
    phone: "+54 11 4444-2202",
    color: "#2784e6",
    isActive: true,
  },
];

export const tenantBlockedTimeSlots = [
  {
    id: "blocked_1",
    title: "Almuerzo del equipo",
    reason: "Pausa interna",
    startsAt: "2026-04-07 13:00",
    startsAtIso: "2026-04-07T13:00:00.000Z",
    endsAtIso: "2026-04-07T14:00:00.000Z",
  },
];

export const tenantPublicProfile: TenantPublicProfile = {
  id: "tenant_dentista",
  name: "Clinica Dental Sonrisa",
  slug: "dentista",
  headline: "Reserva tu turno en pocos pasos",
  description:
    "Selecciona el servicio, elige una fecha disponible y confirma tu turno online.",
  heroLayout: "content-left",
  siteBlocks: [
    {
      id: "block_text_intro",
      type: "text",
      eyebrow: "Atencion profesional",
      title: "Una experiencia simple para reservar con confianza",
      body: "Muestra tus principales beneficios, responde dudas frecuentes y ayuda a que cada visita avance naturalmente hacia la reserva.",
      align: "left",
      titleSize: "xl",
      bodySize: "md",
      tone: "dark",
      width: "wide",
    },
    {
      id: "block_columns_highlights",
      type: "columns",
      layout: "feature-left",
      columns: [
        {
          id: "col_1",
          title: "Horarios claros",
          body: "Los clientes encuentran disponibilidad real y reservan en pocos pasos.",
        },
        {
          id: "col_2",
          title: "Imagen cuidada",
          body: "Tu negocio se presenta con una identidad mucho mas profesional.",
        },
        {
          id: "col_3",
          title: "Gestion ordenada",
          body: "La agenda y los turnos quedan organizados desde una sola plataforma.",
        },
      ],
    },
    {
      id: "block_cta_main",
      type: "cta",
      title: "Reserva tu proximo turno online",
      body: "Elige el servicio, la fecha y el horario disponible que mejor te quede.",
      buttonLabel: "Ver disponibilidad",
      buttonHref: "/reservar",
      titleSize: "lg",
      bodySize: "md",
      theme: "solid",
    },
  ],
  paymentSettings: {
    mercadoPagoEnabled: false,
    hasMercadoPagoAccessToken: false,
    hasMercadoPagoWebhookSecret: false,
  },
  services: [
    {
      id: "srv_1",
      name: "Limpieza dental",
      durationMin: 30,
      priceLabel: "$25.000",
      priceCents: 2500000,
      isActive: true,
      images: [],
    },
    {
      id: "srv_2",
      name: "Control general",
      durationMin: 45,
      priceLabel: "$32.000",
      priceCents: 3200000,
      isActive: true,
      images: [],
    },
    {
      id: "srv_3",
      name: "Blanqueamiento",
      durationMin: 60,
      priceLabel: "$48.000",
      priceCents: 4800000,
      isActive: true,
      images: [],
    },
  ],
  nextSlots: [
    "Martes 7 - 09:00",
    "Martes 7 - 09:30",
    "Martes 7 - 10:00",
    "Miercoles 8 - 14:00",
  ],
};
